### ISSUE TITLE
Section check-marks do not reset for new system

### ISSUE THREAD

**Issue by kshowalter** [FSEC/SPD#26]

**Comment by wmollenkopf** [comment]
It looks like update(); needs to be performed whenever a new system is created since the update function within client\lib\update.js has the function update() that appears to be responsible for setting the icon images properly.

Performing the update(); per new system will likely add some overhead in terms of loading/display time since the page will take a bit to reload everything, but that might be the safest future-proof way of making sure everything is (re-)initialized.

I'm not yet too sure what the best solution is to resolve this though. But figured this much information might help whomever.

**Comment by kshowalter** [comment]
update() is the function that fix things like this, but for your own sanity you should not try to figure out when it and setup_webpage() need to be called. This is why I started looking for alternative template/rendering library.

**Comment by kshowalter** [comment]
It should be fixed in https://github.com/FSEC/SPD/commit/e6336f143cbccd09f18f2353e9a521c03bd35e7d

**Comment by wmollenkopf** [comment]
This appears to be a bug still using.
Tested using Chrome and Firefox.

**Comment by kshowalter** [comment]
Recent changes seem to have fixed it. 

We can reopen this when it breaks again.
